# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9fedb4d384d8bdbe133af9d5939aa80d039bd33c96e511cda391349772bd8faccb7a9f46c9c2d3d18098520fffbb9568616a1380c509768521387cbce7dd7a7

test:
  secret_key_base: 5dec25bfd58e85c5f5a31cbc5c2d7274b5c443a0118710faae8fc1edb63d850646932f04a46c74648453312b5608829e483b7e83338bc57b9100f7b709fa1b4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
